---
name: "o5deploy"

blobstores:
  - name: env-configs

secrets:
  - name: github

databases:
  - name: main
    postgres:
      dbName: o5
      serverGroup: default
      dbExtensions:
        - "uuid-ossp"

      migrateContainer:
        image:
          name: o5-deploy-aws
          registry: ghcr.io/pentops
        command: [migrate]
        envVars:
          - name: "POSTGRES_URL"
            database:
              databaseName: main

runtimes:
  - name: main
    grantMetaDeployPermissions: true
    subscriptions:
      - name: "webhook-github"
        envName: "publicweb"

    containers:
      - name: main
        demand: DEMAND_LIGHT
        image:
            name: o5-deploy-aws
            registry: ghcr.io/pentops
        command: [serve]
        envVars:
          - name: CONFIG_FILE
            blobstore:
              name: env-configs
              s3_direct: true
              subPath: "config.yaml"
          - name: GH_PRIVATE_KEY
            secret:
              secretName: github
              jsonKey: privateKey
          - name: GH_APP_ID
            secret:
              secretName: github
              jsonKey: appId
          - name: GH_INSTALLATION_ID
            secret:
              secretName: github
              jsonKey: installationId


