---
name: "o5deploy"

blobstores:
  - name: env-configs

secrets:
  - name: github

runtimes:
  - name: main
    routes:
      - prefix: "/githubwebhook"
        protocol: ROUTE_PROTOCOL_HTTP
        target_container: main
        bypass_ingress: true
        port: 8080
    containers:
      - name: main
        demand: DEMAND_LIGHT
        image:
            name: o5-deploy-aws
            registry: ghcr.io/pentops
        command: [serve]
        envVars:
          - name: WEBHOOK_PORT
            value: "8080"
          - name: ENV_CONFIG
            blobstore:
              name: env-configs
              s3_direct: true
              subPath: "devcore.yaml"
          - name: GITHUB_WEBHOOK_SECRET
            secret:
              secretName: github
              jsonKey: webhookSecret
          - name: GH_PRIVATE_KEY
            secret:
              secretName: github
              jsonKey: privateKey
          - name: GH_APP_ID
            secret:
              secretName: github
              jsonKey: appId
          - name: GH_INSTALLATION_ID
            secret:
              secretName: github
              jsonKey: installationId


