---
name: "o5deploy"

blobstores:
  - name: env-configs

secrets:
  - name: github

runtimes:
  - name: main
    subscriptions:
      - name: "webhook-github"
    containers:
      - name: main
        demand: DEMAND_LIGHT
        image:
            name: o5-deploy-aws
            registry: ghcr.io/pentops
        command: [serve]
        envVars:
          - name: ENV_CONFIG
            blobstore:
              name: env-configs
              s3_direct: true
              subPath: "devcore.yaml"
          - name: GH_PRIVATE_KEY
            secret:
              secretName: github
              jsonKey: privateKey
          - name: GH_APP_ID
            secret:
              secretName: github
              jsonKey: appId
          - name: GH_INSTALLATION_ID
            secret:
              secretName: github
              jsonKey: installationId


